# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import killfeed_detection_pb2 as killfeed__detection__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in killfeed_detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KillfeedDetectionServiceStub(object):
    """Service for detecting killfeeds and determining their status
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessFrame = channel.unary_unary(
                '/killfeed.KillfeedDetectionService/ProcessFrame',
                request_serializer=killfeed__detection__pb2.ProcessFrameRequest.SerializeToString,
                response_deserializer=killfeed__detection__pb2.ProcessFrameResponse.FromString,
                _registered_method=True)


class KillfeedDetectionServiceServicer(object):
    """Service for detecting killfeeds and determining their status
    """

    def ProcessFrame(self, request, context):
        """Process a frame to detect killfeeds and determine status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KillfeedDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFrame,
                    request_deserializer=killfeed__detection__pb2.ProcessFrameRequest.FromString,
                    response_serializer=killfeed__detection__pb2.ProcessFrameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'killfeed.KillfeedDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('killfeed.KillfeedDetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KillfeedDetectionService(object):
    """Service for detecting killfeeds and determining their status
    """

    @staticmethod
    def ProcessFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/killfeed.KillfeedDetectionService/ProcessFrame',
            killfeed__detection__pb2.ProcessFrameRequest.SerializeToString,
            killfeed__detection__pb2.ProcessFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
