# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: killfeed_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'killfeed_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18killfeed_detection.proto\x12\x08killfeed\"2\n\x08\x46rameAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"U\n\x13ProcessFrameRequest\x12\x13\n\x0b\x66rame_image\x18\x01 \x01(\x0c\x12\x13\n\x0b\x66rame_width\x18\x02 \x01(\x05\x12\x14\n\x0c\x66rame_height\x18\x03 \x01(\x05\"m\n\x14ProcessFrameResponse\x12-\n\ndetections\x18\x01 \x03(\x0b\x32\x19.killfeed.DetectionResult\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x8c\x01\n\x0f\x44\x65tectionResult\x12\x15\n\rcropped_image\x18\x01 \x01(\x0c\x12\x0e\n\x06status\x18\x02 \x01(\t\x12#\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32\x15.killfeed.BoundingBox\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x19\n\x11\x64\x65tection_sources\x18\x05 \x03(\t\"=\n\x0b\x42oundingBox\x12\n\n\x02x1\x18\x01 \x01(\x05\x12\n\n\x02y1\x18\x02 \x01(\x05\x12\n\n\x02x2\x18\x03 \x01(\x05\x12\n\n\x02y2\x18\x04 \x01(\x05\x32i\n\x18KillfeedDetectionService\x12M\n\x0cProcessFrame\x12\x1d.killfeed.ProcessFrameRequest\x1a\x1e.killfeed.ProcessFrameResponse2T\n\x12\x46rameIngestService\x12>\n\tSendFrame\x12\x1d.killfeed.ProcessFrameRequest\x1a\x12.killfeed.FrameAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'killfeed_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEACK']._serialized_start=38
  _globals['_FRAMEACK']._serialized_end=88
  _globals['_PROCESSFRAMEREQUEST']._serialized_start=90
  _globals['_PROCESSFRAMEREQUEST']._serialized_end=175
  _globals['_PROCESSFRAMERESPONSE']._serialized_start=177
  _globals['_PROCESSFRAMERESPONSE']._serialized_end=286
  _globals['_DETECTIONRESULT']._serialized_start=289
  _globals['_DETECTIONRESULT']._serialized_end=429
  _globals['_BOUNDINGBOX']._serialized_start=431
  _globals['_BOUNDINGBOX']._serialized_end=492
  _globals['_KILLFEEDDETECTIONSERVICE']._serialized_start=494
  _globals['_KILLFEEDDETECTIONSERVICE']._serialized_end=599
  _globals['_FRAMEINGESTSERVICE']._serialized_start=601
  _globals['_FRAMEINGESTSERVICE']._serialized_end=685
# @@protoc_insertion_point(module_scope)
