# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: killfeed.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'killfeed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekillfeed.proto\x12\x0bkillfeed.v1\"e\n\nRowTimings\x12\x0f\n\x07prep_ms\x18\x01 \x01(\x01\x12\x0f\n\x07jpeg_ms\x18\x02 \x01(\x01\x12\x0e\n\x06ocr_ms\x18\x03 \x01(\x01\x12\x13\n\x0bmetadata_ms\x18\x04 \x01(\x01\x12\x10\n\x08total_ms\x18\x05 \x01(\x01\"\xd9\x01\n\x0bKillfeedRow\x12*\n\nevent_type\x18\x01 \x01(\x0e\x32\x16.killfeed.v1.EventType\x12\x0e\n\x06killer\x18\x02 \x01(\t\x12\x0e\n\x06victim\x18\x03 \x01(\t\x12\x11\n\tbbox_xyxy\x18\x04 \x03(\x05\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x17\n\x0f\x64\x65tection_class\x18\x06 \x01(\t\x12\x11\n\tcrop_jpeg\x18\x07 \x01(\x0c\x12+\n\ntimings_ms\x18\x08 \x01(\x0b\x32\x17.killfeed.v1.RowTimings\"q\n\x0cInferRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x11\n\x04\x63onf\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12\x1f\n\x12min_killblock_conf\x18\x03 \x01(\x02H\x01\x88\x01\x01\x42\x07\n\x05_confB\x15\n\x13_min_killblock_conf\"\xc1\x01\n\rInferResponse\x12\x14\n\x0cprocessed_at\x18\x01 \x01(\t\x12\x15\n\rdecode_failed\x18\x02 \x01(\x08\x12\x1b\n\x13raw_killblock_count\x18\x03 \x01(\x05\x12\x11\n\tdecode_ms\x18\x04 \x01(\x01\x12\x11\n\tdetect_ms\x18\x05 \x01(\x01\x12\x18\n\x10rows_pipeline_ms\x18\x06 \x01(\x01\x12&\n\x04rows\x18\x07 \x03(\x0b\x32\x18.killfeed.v1.KillfeedRow*i\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x45VENT_TYPE_KILL\x10\x01\x12\x14\n\x10\x45VENT_TYPE_KNOCK\x10\x02\x12\x15\n\x11\x45VENT_TYPE_REVIVE\x10\x03\x32J\n\x08Killfeed\x12>\n\x05Infer\x12\x19.killfeed.v1.InferRequest\x1a\x1a.killfeed.v1.InferResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'killfeed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTTYPE']._serialized_start=665
  _globals['_EVENTTYPE']._serialized_end=770
  _globals['_ROWTIMINGS']._serialized_start=31
  _globals['_ROWTIMINGS']._serialized_end=132
  _globals['_KILLFEEDROW']._serialized_start=135
  _globals['_KILLFEEDROW']._serialized_end=352
  _globals['_INFERREQUEST']._serialized_start=354
  _globals['_INFERREQUEST']._serialized_end=467
  _globals['_INFERRESPONSE']._serialized_start=470
  _globals['_INFERRESPONSE']._serialized_end=663
  _globals['_KILLFEED']._serialized_start=772
  _globals['_KILLFEED']._serialized_end=846
# @@protoc_insertion_point(module_scope)
