# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: killfeed_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'killfeed_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16killfeed_service.proto\x12\x08killfeed\"3\n\x0ePredictRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x12\n\nenable_ocr\x18\x02 \x01(\x08\"9\n\x07OCRText\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0c\n\x04\x62\x62ox\x18\x03 \x03(\x02\"\xab\x01\n\tDetection\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x0c\n\x04\x62\x62ox\x18\x04 \x03(\x02\x12\x19\n\x11\x63ropped_image_url\x18\x05 \x01(\t\x12$\n\tocr_texts\x18\x06 \x03(\x0b\x32\x11.killfeed.OCRText\x12\x15\n\rcombined_text\x18\x07 \x01(\t\"O\n\x0fPredictResponse\x12\'\n\ndetections\x18\x01 \x03(\x0b\x32\x13.killfeed.Detection\x12\x13\n\x0bocr_time_ms\x18\x02 \x01(\x02\x32Z\n\x18KillfeedDetectionService\x12>\n\x07Predict\x12\x18.killfeed.PredictRequest\x1a\x19.killfeed.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'killfeed_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=36
  _globals['_PREDICTREQUEST']._serialized_end=87
  _globals['_OCRTEXT']._serialized_start=89
  _globals['_OCRTEXT']._serialized_end=146
  _globals['_DETECTION']._serialized_start=149
  _globals['_DETECTION']._serialized_end=320
  _globals['_PREDICTRESPONSE']._serialized_start=322
  _globals['_PREDICTRESPONSE']._serialized_end=401
  _globals['_KILLFEEDDETECTIONSERVICE']._serialized_start=403
  _globals['_KILLFEEDDETECTIONSERVICE']._serialized_end=493
# @@protoc_insertion_point(module_scope)
